---
# tasks file for centos
- name: Copy MongoDB repository
  copy: 
      src=files/mongodb-org-4.4.repo
      dest=/etc/yum.repos.d/mongodb-org-4.4.repo

- name: Install Pymongo
  pip:
      name=pymongo

- name: Install MongoDB
  ansible.builtin.dnf: 
    name="mongodb-org, mongodb-org-server"
    state=latest
    update_cache=yes
 
- name: remove mongod default a file
  file:
    path: /etc/mongod.conf
    state: absent
 
- name: create /db directory
  file:
    path: /data/db
    state: directory
 
- name: mongod conf copy
  template:
    src: mongodc.j2
    dest: /etc/mongod.conf
