---
# tasks file for mongodb

- include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: centos.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: alpine.yml
  when: ansible_os_family == 'Alpine'