---
# tasks file for mongodb

- include_vars: credentials.yml 

- name: Put the credentials in the tmp directory on the remote server.
  copy:
    content="{{mongo_login}}, {{mongo_password}}"
    dest=/tmp/credentials.txt

- name: Install and configure MongoDB
  block:
    - include_tasks: centos.yml
      #when: ansible_os_family == 'RedHat'
  tags: deploy

- name: Configure replica set
  include: replica.yml
  tags: restart