---

- block:
  - name: Create database user
    community.mongodb.mongodb_user:
      database: "admin"
      name: "admin_user"
      password: "test"
      state: present

  - name: initiate replica set
    community.mongodb.mongodb_replicaset:
      replica_set: "rs0"
      login_host: "173.19.0.2"
      login_port: "27017"
      login_user: "test_user"
      login_password: "test"
      members:
      - 173.19.0.3
      - 173.19.0.4
      validate: no